project_id = "oectjdngvrqnxwhnwfrt"

[functions.track-visit]
verify_jwt = false

[functions.fetch-exchange-rates]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.og-image]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.notify-restock]
verify_jwt = false
